# Generated by Django 4.1 on 2022-08-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="material",
            name="mesurements",
            field=models.ManyToManyField(
                related_name="material_mesurement_methods",
                to="materials.measurementmethod",
            ),
        ),
    ]
