# Generated by Django 4.1 on 2022-08-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_materialusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialusage",
            name="price",
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
