# Generated by Django 4.1 on 2022-08-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_materialusage_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialusage",
            name="price_currency",
            field=models.CharField(default="UGX", max_length=10),
        ),
    ]
