# Generated by Django 4.1 on 2022-08-29 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_material_added_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="added_date",
        ),
        migrations.AddField(
            model_name="materialusage",
            name="added_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
