# Generated by Django 4.1 on 2022-08-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival_time", models.DateTimeField()),
                ("departure_time", models.DateTimeField()),
                ("daily_rate", models.IntegerField()),
                ("daily_rate_currency", models.CharField(default="UGX", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workers.worker"
                    ),
                ),
            ],
        ),
    ]
