# Generated by Django 4.1 on 2022-08-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0002_dailywork"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailywork",
            name="added_date",
            field=models.DateField(auto_now_add=True, default="2022-08-22"),
            preserve_default=False,
        ),
    ]
