# Generated by Django 4.1 on 2022-08-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0003_dailywork_added_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailywork",
            name="departure_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
