# Generated by Django 4.1 on 2022-08-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0004_alter_dailywork_departure_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailywork",
            name="arrival_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="dailywork",
            name="departure_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
