# Generated by Django 4.1 on 2022-08-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0005_alter_dailywork_arrival_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailywork",
            name="arrival_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="dailywork",
            name="departure_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
